export const WebHomeLocator = {
    registerButton: "//div[contains(text(),'Đăng ký')]",
    nameTxt: "//input[@name='fullName']",
    registerPopup: "//h2[contains(text(),'Thông tin đăng ký')]",
    emailTxt: "//input[@name='email']",
    phoneTxt: "//input[@placeholder='Số điện thoại']",
    passwordTxt: "//input[@name='password']",
    confirmPasswordTxt: "//input[@name='confirmPassword']",
    submit: "//button[contains(@type,'submit')]//div[contains(text(),'Đăng ký')]",
    confirmPopup: "//div[text()='Xác thực tài khoản']",
    confirmCodeTxt: "//input[contains(@aria-label,'Character %')]",
    confirmButton: "//button[contains(.,'Xác nhận')]",
    msgErrorConfirmCode: "//div[contains(text(),'Mã xác thực không hợp lệ')]",
    loginButton: "//div[contains(text(),'Đăng nhập')]",
    usernameTxt: "//input[@id='email']",
    loginPasswordTxt: "//input[@id='password']",
    loginSubmitBtn: "//button[contains(@type,'submit')]",
    loginPopup: "//h1[contains(text(),'Đăng nhập')]",
    khoaHocCuaToiBtn: "//div[contains(@class,'w-39')]//div[contains(text(),'Khoá học của tôi')]",
    avaUser: "//span[contains(@class,'ant-avatar')]/parent::div",
    logoutBtn: "//div[contains(@class,'ant-dropdown')]//p[contains(text(),'Đăng xuất')]",
    confirmLogoutBtn: "//span[contains(text(),'Đồng ý')]",
    loginBtn: "//div[contains(text(),'Đăng nhập')]",
    loginPopupBtn: "//button[@type='submit']",
    usernameField: "//input[@id='email']",
    passwordField: "//input[@id='password']",
    myCourseBtn: "//div[contains(text(),'Khoá học của tôi')]",
    selfStudyCourseMenu: "//span[contains(text(),'Khóa tự học')]",
    selfStudyCourseSubMenu: "(//a[contains(text(), 'Tiếng Anh')])[2]",
    examReviewToolMenu: "//span[contains(text(),'Công cụ ôn thi')]",
    examReviewToolSubMenu: "//a[contains(text(), 'Tin học')]",
};