export const BuyExamReviewLocators = {
    selfStudyCourseTitle: "//h1[contains(text(),'Tin học')]",
    selfStudyCourseDetailBtn: "//a[text()='Đề thi thử IC3 Spark - GS4 (10 lượt TEST)']/parent::div//button",
    selfStudyCourseDetailTitle: "//h2[text()='Đề thi thử IC3 Spark']",
    addToCartBtn: "//div[contains(text(),'Thêm vào giỏ hàng')]",
    cartIcon: "//span[contains(@class,'border-none cursor-pointer')]//*[name()='svg']",
    cartDetail: "//h3[contains(text(),'Giỏ hàng')]",
    buyBtn: "//div[text()='Mua hàng']",
    orderBtn: "//div[text()='Đặt hàng']",
    paymentMethodTitle: "//h3[contains(text(),'Chọn phương thức thanh toán')]",
    checkboxPaymentTerms: "//span[contains(text(),'Tôi đồng ý với các điều khoản thanh toán')]",
    paymentBtn: "//div[normalize-space()='Thanh toán']",
    paymentMethodBankAccountTitle: "//div[contains(text(),'Thẻ nội địa và tài khoản ngân hàng')]",
    ncbBankBtn: "//div[@search-value='ngan hang ncb']",
    paymentViaNCBBankTitle: "//div[@class='right-bill-col-inner']//div[contains(text(),'Thanh toán qua Ngân hàng NCB')]",
    cardNumberTxt: "//input[@id='card_number_mask']",
    cardHolderTxt: "//input[@id='cardHolder']",
    cardDateTxt: "//input[@id='cardDate']",
    continueButton: "//button[@id='btnContinue']",
    otpTxt: "//input[@id='otpvalue']",
    payBtn: "//button[@id='btnConfirm']",
    paymentSuccessTitle: "//h1[normalize-space()='Thanh toán thành công!']",
};
