export const SeflStudyCourseLocators = {
    cartIcon: "//span[contains(@class,'border-none cursor-pointer')]//*[name()='svg']",
    selfStudyCourseTitle: "//h1[contains(text(),'Tiếng Anh')]",
    selfStudyCourseDetailBtn: "//a[text()='TOEIC Compact Online 450+']/parent::div//button",
    selfStudyCourseDetailTitle: "//h2[text()='TOEIC Compact Online 450+']",
    addToCartBtn: "//div[contains(text(),'Thêm vào giỏ hàng')]",
    cartDetail: "//h3[contains(text(),'Giỏ hàng')]",
    buyBtn: "//div[text()='Mua hàng']",
    orderBtn: "//div[text()='Đặt hàng']",
    paymentMethodTitle: "//h3[contains(text(),'Chọn phương thức thanh toán')]",
    checkboxPaymentTerms: "//span[contains(text(),'Tôi đồng ý với các điều khoản thanh toán')]",
    paymentBtn: "//div[normalize-space()='Thanh toán']",
    paymentMethodBankAccountTitle: "//div[contains(text(),'Thẻ nội địa và tài khoản ngân hàng')]",
    ncbBankBtn: "//div[@search-value='ngan hang ncb']",
    paymentViaNCBBankTitle: "//div[@class='right-bill-col-inner']//div[contains(text(),'Thanh toán qua Ngân hàng NCB')]",
    cardNumberTxt: "//input[@id='card_number_mask']",
    cardHolderTxt: "//input[@id='cardHolder']",
    cardDateTxt: "//input[@id='cardDate']",
    continueButton: "//button[@id='btnContinue']",
    otpTxt: "//input[@id='otpvalue']",
    payBtn: "//button[@id='btnConfirm']",
    paymentSuccessTitle: "//h1[normalize-space()='Thanh toán thành công!']",
    startLessonBtn: "//div[contains(text(),'TOEIC Compact Online 450+ ')]/parent::div//button",
    nameCourseTitle: "//h1[contains(text(),'TOEIC Compact Online 450')]",
    unit2: "(//div[contains(@class,'relative w-full overflow-hidden aspect-video')])[2]",
    redoBtn: "//button[normalize-space()='Redo']",
    viewResultBtn: "//button[normalize-space()='View result']",
    testResultTitle: "//h1[text()='Test result']",
    seeResultBtn: "//button[normalize-space()='See answers']",
    correctAnswerLabel: "//button[normalize-space()='See answers']",
};